<?php

/**
 * Implements hook_permissions
 */
function drupanium_debug_permission() {
  return array(
    'access drupanium debug' => array(
      'title' => t('Access Drupanium Debug'), 
      'description' => t('Use Drupanium Debug module'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function drupanium_debug_menu() {
  // General configuration
  $items['drupanium'] = array(
    'title' => 'Drupanium debug',
    'description' => 'Debug drupanium',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupanium_debug_intro_page'),
    'access arguments' => array("access drupanium debug"),
    'type' => MENU_NORMAL_ITEM,
  );
  
  // Search node
  $items['drupanium/search_node'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Search node',
    'page callback' => 'drupal_get_form',
    'page arguments' => array("drupanium_debug_search_node_page"),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'search_node.inc',
  );
  
  $items['drupanium/search_node/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupanium_debug_search_node_page_results',
    'page arguments' => array(2),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'search_node.inc',
  );
  
  // Get node
  $items['drupanium/node_get'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Node get',
    'page callback' => 'drupal_get_form',
    'page arguments' => array("drupanium_debug_node_get_page"),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'node_get.inc',
  );
  
  $items['drupanium/node_get/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupanium_debug_node_get_page_results',
    'page arguments' => array(2),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'node_get.inc',
  );
  
  // Get node comments
  $items['drupanium/node_get_comments'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Node get comments',
    'page callback' => 'drupal_get_form',
    'page arguments' => array("drupanium_debug_node_get_comments_page"),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'node_get_comments.inc',
  );
  
  $items['drupanium/node_get_comments/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupanium_debug_node_get_comments_page_results',
    'page arguments' => array(2),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'node_get_comments.inc',
  );
  
  // Get comment
  $items['drupanium/comment_get'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Comment get',
    'page callback' => 'drupal_get_form',
    'page arguments' => array("drupanium_debug_comment_get_page"),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'comment_get.inc',
  );
  
  $items['drupanium/comment_get/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupanium_debug_comment_get_page_results',
    'page arguments' => array(2),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'comment_get.inc',
  );
  
  // Search user 
  $items['drupanium/search_user'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Search users',
    'page callback' => 'drupal_get_form',
    'page arguments' => array("drupanium_debug_search_user_page"),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'search_user.inc',
  );
  
  $items['drupanium/search_user/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupanium_debug_search_user_page_results',
    'page arguments' => array(2),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'search_user.inc',
  );
  
  // Search user 
  $items['drupanium/user'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Get user',
    'page callback' => 'drupal_get_form',
    'page arguments' => array("drupanium_debug_user_page"),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'user.inc',
  );
  
  $items['drupanium/user/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'drupanium_debug_user_page_results',
    'page arguments' => array(2),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'user.inc',
  );
  
  // Search user 
  $items['drupanium/user_create'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Create user',
    'page callback' => 'drupal_get_form',
    'page arguments' => array("drupanium_debug_user_create_page"),
    'access arguments' => array("access drupanium debug"),
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'user_create.inc',
  );
  
  // Views
  $items['drupanium/views'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupanium_debug_views_page',
    'access arguments' => array("access drupanium debug"),
    'title' => 'Views',
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'views.inc',
  );
  
  // Login
  $items['drupanium/login'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupanium_debug_user_login_page'),
    'access arguments' => array("access drupanium debug"),
    'title' => 'Login',
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'login.inc',
  );
  
  // Login
  $items['drupanium/create_content'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupanium_debug_create_content_page'),
    'access arguments' => array("access drupanium debug"),
    'title' => 'Create content',
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'create_content.inc',
  );
  
  // isflag
  $items['drupanium/flag'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupanium_debug_flag_page'),
    'access arguments' => array("access drupanium debug"),
    'title' => 'Flag a node',
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'flag.inc',
  );
  
  // isflag
  $items['drupanium/isflag'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupanium_debug_isflag_page'),
    'access arguments' => array("access drupanium debug"),
    'title' => 'Is flagged',
    'file path' => drupal_get_path("module", "drupanium_debug") . '/includes',
    'file' => 'flag.inc',
  );
  
  return $items;
}

/**
 * Default and intro callback
 */
function drupanium_debug_intro_page($form) {
	global $base_url;
	
  $form = array();
	
	$form['message'] = array(
		'#markup' => '<p>' . t("Configure the following paths. Those paths will be used to demonstrate functionality. If you have Drupanium installed on this site is recommended to leave the default paths. Be aware that any possible error might be caused by wrong paths set here so be careful and double check them before you submit a bug. Please save the configuration as it is so Drupanium can detect the paths.") . '</p>',
	);
  
  $form['drupanium_url'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server"),
    '#default_value' => variable_get("drupanium_url", $base_url . '/api/rest/'),
    '#description' => t("Enter the full URI to the REST Server of the site, this will be used for some services")
  );
  
  $form['drupanium_search_node'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server / Search Node Resource"),
    '#default_value' => variable_get("drupanium_search_node", $base_url . '/api/rest/search_node/retrieve.json'),
    '#description' => t("Enter the full URI to the REST Server and the search node retrieve resource")
  );
  
  $form['drupanium_search_user'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server / Search User Resource"),
    '#default_value' => variable_get("drupanium_search_user", $base_url . '/api/rest/search_user/retrieve.json'),
    '#description' => t("Enter the full URI to the REST Server and the search user retrieve resource")
  );
  
  $form['drupanium_node'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server / Node Resource"),
    '#default_value' => variable_get("drupanium_node", $base_url . '/api/rest/node/'),
    '#description' => t("Enter the full URI to the REST Server and the node resource")
  );
  
  $form['drupanium_comment'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server / Comments Resource"),
    '#default_value' => variable_get("drupanium_comment", $base_url . '/api/rest/comment/'),
    '#description' => t("Enter the full URI to the REST Server and the comment resource")
  );
  
  $form['drupanium_user'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server / User Get Resource"),
    '#default_value' => variable_get("drupanium_user", $base_url . '/api/rest/user/'),
    '#description' => t("Enter the full URI to the REST Server and user get resource")
  );
  
  $form['drupanium_user_login'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server / Login Resource"),
    '#default_value' => variable_get("drupanium_user_login", $base_url . '/api/rest/user/login/'),
    '#description' => t("Example: http://example.com/api/rest/user/login")
  );
  
  $form['drupanium_views'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server / Views Resource"),
    '#default_value' => variable_get("drupanium_views", $base_url . '/api/rest/views/content.json'),
    '#description' => t("Enter the full URI to the REST Server and the views retrieve resource")
  );
  
  $form['drupanium_create_content'] = array(
    '#type' => 'textfield',
    '#title' => t("URI to REST Server / Create content"),
    '#default_value' => variable_get("drupanium_create_content", $base_url . '/api/rest/node/'),
    '#description' => t("Enter the full URI to the REST Server and the create node resource")
  );
  
  
  
  return system_settings_form($form);
}


